image: node:12.14.1-alpine

stages:
  - before-deploy
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run build

build-docker-image:
  stage: before-deploy
  script:
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/pickat/pickat-backend .
  # only:
  #   - master
