version: "3.6"
services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
        - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    # volumes:
    #   - ${POSTGRES_HOME_DIR}/data/:/var/lib/postgresql/data
