branch-defaults:
  default:
    environment: staging
  master:
    environment: staging
  production:
    environment: prod
global:
  application_name: Tastie-Backend
  default_region: ap-northeast-2
  profile: eb-cli
