branch-defaults:
  3-setup-api-environment-for-develop:
    environment: staging
global:
  application_name: pickat-backend
  branch: null
  default_ec2_keyname: null
  default_platform: docker
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
option_settings:
  aws:autoscaling:launchconfiguration:
    InstanceType: t3.micro
