on: [workflow_dispatch]
name: DB migration for alpha

jobs:
  migrate:
    runs-on: ubuntu-20.04
    env:
      DB_HOST: ${{ secrets.ALPHA_DB_HOST }}
      DB_USERNAME: ${{ secrets.ALPHA_DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.ALPHA_DB_PASSWORD }}
      DB_DBNAME: ${{ secrets.ALPHA_DB_DBNAME }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM packages
        run: npm install
      - name: Run migration script
        run: npm run typeorm:run
