on: [push]
name: Build And Push

env:
  AWS_ECR_REPO: 'tastie/backend'
  AWS_REGION: ap-northeast-1

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        id: get-version
        env:
          SHA: ${{ github.sha }}
        run: |
          echo "::set-output name=version::${SHA}"

      - name: Build docker image
        env:
          DOCKER_BUILDKIT: 1
          IMAGE_TAG: ${{ steps.get-version.outputs.version }}
        run: docker build -t app .
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: ${{ github.event.repository.default_branch == github.ref_name }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        if: ${{ github.event.repository.default_branch == github.ref_name }}
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push docker image
        env:
          IMAGE_TAG: ${{ steps.get-version.outputs.version }}
          GITHUB_BRANCH: ${{ github.ref }}
          AWS_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        # when ref is default branch
        if: ${{ github.event.repository.default_branch == github.ref_name }}
        run: |
          docker tag app $AWS_ECR_REGISTRY/$AWS_ECR_REPO:$IMAGE_TAG
          docker push $AWS_ECR_REGISTRY/$AWS_ECR_REPO:$IMAGE_TAG